services:
  backend:
    build:
      context: ../go
      dockerfile: Dockerfile
    container_name: go-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file: "../../.env"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://82.202.137.111:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
