services:
  backend:
    build:
      context: ../go
      dockerfile: Dockerfile
    container_name: go-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file: "../../.env"
    networks:
      - app-network
