services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_app
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://copilot-llm-python:8000
      - NEXT_PUBLIC_AUTH_API_URL=http://go-backend:8080
    networks:
      - app-network
    depends_on:
      - app
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--quiet',
          '--tries=1',
          '--spider',
          'http://localhost:3000',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
