services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: copilot-llm-python
    restart: unless-stopped
    ports:
      - '8000:8000'
    env_file:
      - ../../.env
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:8000/health || exit 1']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
