services:
  db:
    build:
      context: ../db
      dockerfile: Dockerfile
    container_name: postgres_db
    restart: unless-stopped
    env_file: "../.env"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data:rw
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-db}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    command:
      - "postgres"
      - "-c"
      - "log_min_messages=warning"
