version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: copilot-llm-python
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ../../.env
    volumes:
      - ./:/app:delegated
    networks:
      - app-network
    command: make run
